apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cache-server
  name: cache-server
  selfLink: /api/v1/namespaces/default/services/cache-server
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: cache-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}