apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cache-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.12.9
    path: "/volume1/KuberData/Apps/RedisCache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cache-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi