apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-01-07T13:31:35Z
    labels:
      app: cache-server
    name: cache-server
    namespace: default
    resourceVersion: "38859"
    selfLink: /api/v1/namespaces/default/services/cache-server
    uid: 152be86f-f3af-11e7-b75a-005056ad227f
  spec:
    clusterIP: 10.98.140.1
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 30303
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: cache-server
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-01-07T05:22:21Z
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "48"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: bcd41f83-f36a-11e7-b75a-005056ad227f
  spec:
    clusterIP: 10.96.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
