apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2018-01-07T13:31:35Z
    generation: 1
    labels:
      app: cache-server
    name: cache-server
    namespace: default
    resourceVersion: "3898143"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/cache-server
    uid: 15275f63-f3af-11e7-b75a-005056ad227f
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: cache-server
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cache-server
      spec:
        containers:
        - image: funky81/redis-template:4.0.6-2.1.2r-1
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: shared-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /shared-data
            type: Directory
          name: shared-data
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2018-01-07T13:31:35Z
      lastUpdateTime: 2018-01-07T13:31:37Z
      message: ReplicaSet "cache-server-5c58bf76f4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2018-02-19T20:49:17Z
      lastUpdateTime: 2018-02-19T20:49:17Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
