apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ws-prod
  name: ws-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ws-prod
      name: ws-pro
    spec:
      containers:
      - image: microsoft/aspnet:4.7.1-windowsservercore-1709
        imagePullPolicy: IfNotPresent
        name: ws-prod
        resources:
          requests:
            cpu: "2"
            memory: 1Gi
        volumeMounts:
        - name: wwwroot
          mountPath: "C:\\inetpub\\wwwroot"
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: mssqlport
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: mssqlport
          initialDelaySeconds: 20
          periodSeconds: 3 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: wwwroot
        hostPath:
          path: "C:\\data\\hubservicesV1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}