apiVersion: v1
kind: Service
metadata:
  labels:
    app: ws-prod
  name: ws-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ws-prod
  sessionAffinity: None
  type: NodePort