# Changes
# 16/2/2017
# - Added default NodePort
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mssql
  name: mssql
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
    nodePort: 31729
  selector:
    run: mssql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}