#Changes
# - Added Enterprise Edition
# - Added NFS Path for data location
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: mssql
  name: mssql
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mssql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mssql
    spec:
      containers:
      - env:
        - name: MSSQL_PID
          value: "Enterprise"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: P4ssw0rd123
        image: docker.io/microsoft/mssql-server-linux:2017-latest
        imagePullPolicy: IfNotPresent
        name: mssql
        ports:
        - name: mssqlport
          containerPort: 1433
          protocol: TCP
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
        readinessProbe:
          tcpSocket:
            port: mssqlport
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: mssqlport
          initialDelaySeconds: 20
          periodSeconds: 3 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: nfs-mssql
            mountPath: "/var/opt/mssql/data/"
      volumes:
      - name: nfs-mssql
        persistentVolumeClaim:
          claimName: nfs-mssql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
