apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mssql
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.12.9
    path: "/volume1/KuberData/SQLServer-Prod"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mssql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi